### ISSUE TITLE
[Chore]: Potential infinite recursion in ginkgo fail handler

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1254]
### Background

*Build URL*: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-periodic/builds/75

*Logs*:  The log file is too big (crashed the browser), and contains the following:
```
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
    Failure correlation ID: "9cc232ec-b09b-41d0-8c78-cf2337101f53"
[SynchronizedAfterSuite]! [INTERRUPTED] [3468.225 seconds]
[SynchronizedAfterSuite]
/tmp/build/3e139e9d/korifi/tests/e2e/e2e_suite_test.go:248

  Interrupted by Timeout

  Here's a stack trace of all running goroutines:
    goroutine 13 [running]:
    github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).InterruptMessageWithStackTraces(0xc000544e10)
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/interrupt_handler/interrupt_handler.go:203 +0x2ac
    github.com/onsi/ginkgo/v2/internal.(*Suite).runNode(_, {0x7, 0x1000, {0x0, 0x0}, 0x2759c18, {{0x2dd381d, 0x36}, 0xf8, {0x0, ...}, ...}, ...}, ...)
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/suite.go:609 +0xc12
    github.com/onsi/ginkgo/v2/internal.(*Suite).runSuiteNode(0xc0001ae000, {0x7, 0x1000, {0x0, 0x0}, 0x0, {{0x2dd381d, 0x36}, 0xf8, {0x0, ...}, ...}, ...}, ...)
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/suite.go:503 +0x17d8
    github.com/onsi/ginkgo/v2/internal.(*Suite).runAfterSuiteCleanup(0xc0001ae000, 0x82)
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/suite.go:362 +0x465
    github.com/onsi/ginkgo/v2/internal.(*Suite).runSpecs(0xc0001ae000, {0x266cb44, 0x9}, {0x37b3b68, 0x0, 0x0}, {0xc0000457d0, 0x24}, 0x0, {0xc00072e000, ...})
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/suite.go:313 +0x685
    github.com/onsi/ginkgo/v2/internal.(*Suite).Run(_, {_, _}, {_, _, _}, {_, _}, _, {0x29f76f8, ...}, ...)
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/suite.go:83 +0x425
    github.com/onsi/ginkgo/v2.RunSpecs({0x29e28a0, 0xc0004916c0}, {0x266cb44, 0x9}, {0x0, 0x0, 0x0?})
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/core_dsl.go:280 +0x1025
    code.cloudfoundry.org/korifi/tests/e2e_test.TestE2E(0x0?)
        /tmp/build/3e139e9d/korifi/tests/e2e/e2e_suite_test.go:227 +0x5b
    testing.tRunner(0xc0004916c0, 0x2759b60)
        /usr/local/go/src/testing/testing.go:1439 +0x214
    created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1486 +0x725

    goroutine 1 [chan receive, 59 minutes]:
    testing.(*T).Run(0xc000491520, {0x2669e4b, 0x7}, 0x2759b60)
        /usr/local/go/src/testing/testing.go:1487 +0x750
    testing.runTests.func1(0x0?)
        /usr/local/go/src/testing/testing.go:1839 +0x9a
    testing.tRunner(0xc000491520, 0xc0005e9ba0)
        /usr/local/go/src/testing/testing.go:1439 +0x214
    testing.runTests(0xc000251ea0?, {0x3746230, 0x1, 0x1}, {0x40?, 0x7fbdfa761a78?, 0x0?})
        /usr/local/go/src/testing/testing.go:1837 +0x7e5
    testing.(*M).Run(0xc000251ea0)
        /usr/local/go/src/testing/testing.go:1719 +0xa72
    main.main()
        _testmain.go:47 +0x2e5

    goroutine 14 [IO wait]:
    internal/poll.runtime_pollWait(0x7fbdfa759318, 0x72)
        /usr/local/go/src/runtime/netpoll.go:302 +0x89
    internal/poll.(*pollDesc).wait(0xc00053e598, 0xc00001d000?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0xbd
    internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:88
    internal/poll.(*FD).Read(0xc00053e580, {0xc00001d000, 0x1000, 0x1000})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x415
    net.(*netFD).Read(0xc00053e580, {0xc00001d000, 0x1000, 0x1000})
        /usr/local/go/src/net/fd_posix.go:55 +0x51
    net.(*conn).Read(0xc000232518, {0xc00001d000, 0x1000, 0x1000})
        /usr/local/go/src/net/net.go:183 +0xb1
    bufio.(*Reader).Read(0xc000356c00, {0xc0005c58f7, 0x1, 0x9})
        /usr/local/go/src/bufio/bufio.go:236 +0x4db
    io.ReadAtLeast({0x29de840, 0xc000356c00}, {0xc0005c58f7, 0x1, 0x9}, 0x1)
        /usr/local/go/src/io/io.go:331 +0xde
    io.ReadFull(...)
        /usr/local/go/src/io/io.go:350
    encoding/gob.decodeUintReader({0x29de840?, 0xc000356c00?}, {0xc0005c58f7?, 0x9?, 0x9?})
        /usr/local/go/src/encoding/gob/decode.go:120 +0x85
    encoding/gob.(*Decoder).recvMessage(0xc00053e600)
        /usr/local/go/src/encoding/gob/decoder.go:81 +0x7a
    encoding/gob.(*Decoder).decodeTypeSequence(0xc00053e600, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:144 +0xab
    encoding/gob.(*Decoder).DecodeValue(0xc00053e600, {0x230e020?, 0xc0000d4990?, 0xc0006bb558?})
        /usr/local/go/src/encoding/gob/decoder.go:223 +0x285
    encoding/gob.(*Decoder).Decode(0xc00053e600, {0x230e020, 0xc0000d4990})
        /usr/local/go/src/encoding/gob/decoder.go:200 +0x28b
    net/rpc.(*gobClientCodec).ReadResponseHeader(0xc000530360, 0x22fc1a0?)
        /usr/local/go/src/net/rpc/client.go:228 +0x52
    net/rpc.(*Client).input(0xc000356cc0)
        /usr/local/go/src/net/rpc/client.go:109 +0x126
    created by net/rpc.NewClientWithCodec
        /usr/local/go/src/net/rpc/client.go:206 +0x17e

    goroutine 16 [syscall, 59 minutes]:
    os/signal.signal_recv()
        /usr/local/go/src/runtime/sigqueue.go:151 +0x2f
    os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
    created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x51

    goroutine 26 [select]:
    github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts.func1()
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/interrupt_handler/interrupt_handler.go:102 +0xee
    created by github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/interrupt_handler/interrupt_handler.go:99 +0x1fe

    goroutine 27 [select]:
    github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts.func2()
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/interrupt_handler/interrupt_handler.go:127 +0x1c5
    created by github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/interrupt_handler/interrupt_handler.go:122 +0x385

    goroutine 28 [select]:
    github.com/onsi/ginkgo/v2/internal.startPipeFactory(0xc0001d0840, 0xc0000ca1e0)
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/output_interceptor.go:77 +0xc7
    created by github.com/onsi/ginkgo/v2/internal.(*genericOutputInterceptor).ResumeIntercepting
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/output_interceptor.go:143 +0x285

    goroutine 360 [runnable]:
    github.com/go-resty/resty/v2.(*Client).R(...)
        /go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/client.go:386
    code.cloudfoundry.org/korifi/tests/e2e/helpers.(*CorrelatedRestyClient).R(0xc0004436a0)
        /tmp/build/3e139e9d/korifi/tests/e2e/helpers/resty.go:101 +0x6b
    code.cloudfoundry.org/korifi/tests/e2e_test.deleteOrg({0xc000045950, 0x2b})
        /tmp/build/3e139e9d/korifi/tests/e2e/e2e_suite_test.go:289 +0x65
    code.cloudfoundry.org/korifi/tests/e2e_test.glob..func9()
        /tmp/build/3e139e9d/korifi/tests/e2e/e2e_suite_test.go:250 +0x3d
    github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func2()
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/suite.go:596 +0xe8
    created by github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/suite.go:584 +0x8fa

    goroutine 373 [IO wait]:
    internal/poll.runtime_pollWait(0x7fbdfa759228, 0x72)
        /usr/local/go/src/runtime/netpoll.go:302 +0x89
    internal/poll.(*pollDesc).wait(0xc0003ad0f8, 0xc0006c6000?, 0x1)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0xbd
    internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:88
    internal/poll.(*FD).Read(0xc0003ad0e0, {0xc0006c6000, 0x8000, 0x8000})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x415
    os.(*File).read(...)
        /usr/local/go/src/os/file_posix.go:31
    os.(*File).Read(0xc0004b0198, {0xc0006c6000, 0x8000, 0x8000})
        /usr/local/go/src/os/file.go:119 +0xc8
    io.copyBuffer({0x29e1c00, 0xc0004ae000}, {0x29e25a0, 0xc0004b0198}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:426 +0x28b
    io.Copy(...)
        /usr/local/go/src/io/io.go:385
    github.com/onsi/ginkgo/v2/internal.(*genericOutputInterceptor).ResumeIntercepting.func1.1()
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/output_interceptor.go:159 +0x6a
    created by github.com/onsi/ginkgo/v2/internal.(*genericOutputInterceptor).ResumeIntercepting.func1
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/output_interceptor.go:158 +0x508

    goroutine 359 [select]:
    github.com/onsi/ginkgo/v2/internal.(*genericOutputInterceptor).ResumeIntercepting.func1()
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/output_interceptor.go:163 +0x59a
    created by github.com/onsi/ginkgo/v2/internal.(*genericOutputInterceptor).ResumeIntercepting
        /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/internal/output_interceptor.go:153 +0x3fe

  In [SynchronizedAfterSuite] at: /tmp/build/3e139e9d/korifi/tests/e2e/e2e_suite_test.go:248
------------------------------


Summarizing 2 Failures:
  [INTERRUPTED] Service Instances Delete when the user has permissions to delete service instances [It] deletes the service instance
  /tmp/build/3e139e9d/korifi/tests/e2e/service_instances_test.go:118
  [INTERRUPTED] [SynchronizedAfterSuite]
  /tmp/build/3e139e9d/korifi/tests/e2e/e2e_suite_test.go:248

Ran 130 of 130 Specs in 3597.084 seconds
FAIL! - Interrupted by Timeout -- 129 Passed | 1 Failed | 0 Pending | 0 Skipped
```

### Dev Notes

We suspect that the fail handler somehow panics and indirectly causes its recursive invocation, which resuslts in the repeated correlation id log line seen above.

**Comment by georgethebeatle** [comment]
We thought this might be a result of a failed `Expect` in the fail handler, and introduce one that would fail reliably, but it did not reproduce the recursion. Anyway we replaced all `Expects` with printing the error and giving up (ginkgo.Fail is always executed in a defer block). This way at least the real failure that caused the Fail handler to be executed will not be overridden. Let's see if it comes back.
